### PR TITLE
Add support for configurable main thread response threshold

### PR DESCRIPTION
**Pull request by ShridharGoel**
This would allow developers to set a custom threshold time for reporting ANRs.

### CODE REVIEW

**Comment by srtvprateek** [comment]
@ShridharGoel ktlint is failing
run `./gradlew ktlintFormat` locally to check the error

**Comment by ShridharGoel** [comment]
@srtvprateek Updated.

**Review by srtvprateek — APPROVED** [review]

**Comment by ShridharGoel** [comment]
@srtvprateek Thanks for merging the PR, can you create a new release?

**Comment by ShridharGoel** [comment]
@srtvprateek Thanks for merging the PR. Can you create a new release?

**Pull request merged**
